### ISSUE TITLE
graph is not showing up (default background color, no UI)

### ISSUE THREAD

**Issue by megamanenm** [trashhalo/logseq-graph-analysis#82]
I click on the graph analysis button, and nothing shows up. The screen isn't white (like it was the last time I had a similar issue), but is merely the default blue background color, like nothing is loading in. Rebooting my PC and re-indexing the graph doesn't work. I recently updated a bunch of programs all together, I'm on Mint. The built-in Logseq graph view does still work, though.

**Comment by theCalcaholic** [comment]
I encounter the same issue. The following error shows up in the dev console:

```
index.d5959c28.js:72 Uncaught (in promise) Error: loadProgram: error while linking the program.
    at hg (index.d5959c28.js:72:426)
    at t.n (index.d5959c28.js:72:1091)
    at t [as constructor] (index.d5959c28.js:72:2105)
    at new t (index.d5959c28.js:72:4624)
    at new t (index.d5959c28.js:310:15045)
    at new Em (index.d5959c28.js:310:36957)
    at index.d5959c28.js:310:37633
    at Du (index.d5959c28.js:12:50383)
    at Array.map (<anonymous>)
    at index.d5959c28.js:12:54555
```

**Comment by megamanenm** [comment]
> I encounter the same issue. The following error shows up in the dev console:
> 
> ```
> index.d5959c28.js:72 Uncaught (in promise) Error: loadProgram: error while linking the program.
>     at hg (index.d5959c28.js:72:426)
>     at t.n (index.d5959c28.js:72:1091)
>     at t [as constructor] (index.d5959c28.js:72:2105)
>     at new t (index.d5959c28.js:72:4624)
>     at new t (index.d5959c28.js:310:15045)
>     at new Em (index.d5959c28.js:310:36957)
>     at index.d5959c28.js:310:37633
>     at Du (index.d5959c28.js:12:50383)
>     at Array.map (<anonymous>)
>     at index.d5959c28.js:12:54555
> ```

I checked and I have the same thing appear, even before opening the graph view upon launch. Also this appears too after building the graph:

```
⚠️ There are no focusable elements inside the <FocusTrap />

❌ Uncaught (in promise) TypeError: r is not iterable  
    at Pq (index-7b9cf43e.js:349:65)  
    at async (index-7b9cf43e.js:350:14395)

db restored, setting up repo hooks  
:frontend.fs.watcher-handler/preload-homepage "journals/2024_11_04.md"  
:frontend.fs.watcher-handler/initial-watcher "/media/mug/Elements/Logseq graph (main)" {:deleted 0, :total 5282}  
reloading custom.css  
building graph  
graph complete 22043
```

**Comment by megamanenm** [comment]
Tried downgraded both the plugin and logseq, still nothing. Why can't it just go back to how it was when it worked

**Comment by megamanenm** [comment]
It worked flawlessly one time for whatever reason, then I restarted Logseq and it stopped working again. I didn't do anything to make it work then, it just did.

**Comment by bene64** [comment]
I've got the same problem, no rendering of the graph :(

However, I don't get any errors in console, it's just `building graph` followed by `graph complete`.

**Comment by megamanenm** [comment]
It's still not fixed, although very rarely it loads properly and remains functional for the rest of that day (then it breaks tomorrow again). It seems to be random.
